name: HTML/CSS CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        zip -r release.zip *
        gh release create v${{ github.run_number }} release.zip -t "v${{ github.run_number }}" -n "Release v${{ github.run_number }}"