name: HTML/CSS CI/CD

on:
  push:
    branches:
      - main

permissions:  
  contents: write  
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages 
        cdn: pages  
        content: ./project e-comm


    
  
