name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 n
    - name: Use Node.js 20
      uses: actions/setup-node@v3 # Updated to use Node.js 20 
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build
